### ISSUE TITLE
Memory-mapped DM9000A?

### ISSUE THREAD

**Issue by xcvista** [pkerling/dm9000#1]
For one of my boards, I have a memory-mapped DM9000A. How do I modify this code so it can talk to the chip connected in that fashion?

**Comment by yol** [comment]
That depends a lot on how the memory mapping is done, as the DM9000A cannot be connected to a memory bus directly. Refer to the documentation of your board. Basically I'd assume that you have to match all functions that access the DM9000 interface (that is `ethernet_read_register`, `ethernet_write_register`, `ethernet_is_packet_ready`, `ethernet_rx_sync`, `ethernet_dump_rx_sync`, and `ethernet_buffer_tx_sync`) to however you access the DM9000 on your board.

Anyway, the scope of this driver is only to support direct connection of the DM9000A/B/BI to a µC, so I will close this.

**Comment by xcvista** [comment]
Some bigger chips like ATmega162, ATmega128A or ATmega2560 has exposed external bus interface. With some external bus buffers and address decoding logic that interface can be used to extend data memory space.

The board in question has a ATmega128A as the main processor, a XC9500XL CPLD serving as the bus latch and address decoding logic, an IS61C256 SRAM chip mapped to address $8000-$ffff, and this DM9000A mapped at $7c00-$7c0f.
